/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import "./src/backend/bootstrap";
import express from "express";
import path from "path";
import cookieParser from "cookie-parser";
import cors from "cors";
import jwt from "jsonwebtoken";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import { createServer as createViteServer } from "vite";
import { Gender, ProgramStatus, Beneficiary, CustomField, AuditLog, DocumentType, WorkflowHistory } from "./src/types";
import { AdmissionController } from "./src/backend/admission.controller";
import { AdmissionService } from "./src/backend/admission.service";
import { EmailService } from "./src/backend/email.service";
import { initDb, DbRepo } from "./src/backend/db";
import { requireAuth, requireRole, JWT_SECRET, AuthenticatedRequest } from "./src/backend/auth.middleware";
import { PdfService } from "./src/backend/pdf.service";
import { CloudinaryService } from "./src/backend/cloudinary.service";
import { DocumentService } from "./src/backend/document.service";

async function autoGenerateDocuments(beneficiaryId: string, status: string, operator: string) {
  try {
    const list = await DbRepo.getGeneratedDocuments(beneficiaryId);
    
    const generateIfMissing = async (docType: DocumentType) => {
      const alreadyHas = list.some(d => d.documentType === docType);
      if (!alreadyHas) {
        console.log(`[Auto-Gen] Auto generating ${docType} for beneficiary ${beneficiaryId}`);
        await DocumentService.generateDocument(beneficiaryId, docType, operator, false);
      } else {
        console.log(`[Auto-Gen] ${docType} already exists for beneficiary ${beneficiaryId}, skipping auto-generation.`);
      }
    };

    if (status === "ADMITTED") {
      await generateIfMissing(DocumentType.ADMISSION_LETTER);
      await generateIfMissing(DocumentType.ADMISSION_FORM);
    } else if (status === "ACCEPTED") {
      await generateIfMissing(DocumentType.ACCEPTANCE_LETTER);
    } else if (status === "ENROLLED") {
      await generateIfMissing(DocumentType.ENROLLMENT_CONFIRMATION);
    } else if (status === "GRADUATED") {
      await generateIfMissing(DocumentType.COMPLETION_CERTIFICATE);
    }
  } catch (err: any) {
    console.error(`[Auto-Gen] Error during auto document generation for status ${status}:`, err);
  }
}

const app = express();
const PORT = 3000;

const corsOptions = {
  origin: function (origin: any, callback: any) {
    if (!origin) return callback(null, true);

    const allowedPatterns = [
      "localhost",
      "127.0.0.1",
      "uniqueideas-tvet-portal.vercel.app",
      "uniqueideas-tvet-portal.onrender.com",
      "run.app",
      "aistudio"
    ];

    const isAllowed = allowedPatterns.some(pattern => origin.includes(pattern));

    if (isAllowed) {
      return callback(null, true);
    }

    return callback(
      new Error(`CORS blocked for origin: ${origin}`)
    );
  },
  credentials: true,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: [
    "Content-Type",
    "Authorization",
    "X-Requested-With",
    "Cookie"
  ]
};

app.use(cors(corsOptions));
app.options("*", cors(corsOptions));

app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));
app.use(cookieParser());

// Helper to log audit actions inside database
async function logAction(username: string, action: string, details: string) {
  const newLog: AuditLog = {
    id: "log_" + Date.now() + "_" + Math.floor(Math.random() * 1000),
    timestamp: new Date().toISOString(),
    username,
    role: "Operations Manager",
    action,
    details
  };
  await DbRepo.saveAuditLog(newLog);
}

// REST API Endpoints

// Authentication API
app.post("/api/auth/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: "Email and password are required" });
    }

    const normalizedEmail = email.toLowerCase().trim();
    const user = await DbRepo.getUserByEmail(normalizedEmail);

    if (!user) {
      await logAction(normalizedEmail, "SECURITY_FAILED", "Authentication failed: Email not registered");
      return res.status(401).json({ error: "Invalid email or password." });
    }

    // Check account lockout status
    if (user.lockout_until && new Date(user.lockout_until) > new Date()) {
      const remainingSeconds = Math.ceil((new Date(user.lockout_until).getTime() - Date.now()) / 1000);
      const remainingMinutes = Math.ceil(remainingSeconds / 60);
      return res.status(403).json({ 
        error: `Account locked due to 5 consecutive failures. Please try again in ${remainingMinutes} minute(s).` 
      });
    }

    // Verify Password Hash using bcryptjs
    const isMatched = bcrypt.compareSync(password, user.password_hash);
    if (isMatched) {
      // Login Success: Reset security counters
      user.failed_login_attempts = 0;
      user.lockout_until = null;
      await DbRepo.updateUser(user);

      // Generate Jwt Token containing user authorities
      const token = jwt.sign(
        { id: user.id, email: user.email, role: user.role, beneficiaryId: user.beneficiary_id },
        JWT_SECRET,
        { expiresIn: "24h" }
      );

      // Store in PostgreSQL user_sessions track list
      const sessionId = "sess_" + crypto.randomBytes(16).toString("hex");
      const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
      await DbRepo.saveUserSession(sessionId, user.id, token, expiresAt);

      // Set cookie header with HttpOnly parameters
      res.cookie("token", token, {
        httpOnly: true,
        secure: process.env.NODE_ENV === "production",
        sameSite: "strict",
        maxAge: 24 * 60 * 60 * 1000
      });

      await logAction(user.email, "SECURITY_LOGIN", `User established secure session. Role: ${user.role}`);

      return res.json({
        isAuthenticated: true,
        username: user.email.split("@")[0],
        email: user.email,
        role: user.role,
        token: token,
        beneficiaryId: user.beneficiary_id || null
      });
    } else {
      // Incorrect password: increment lockout counter
      user.failed_login_attempts = (user.failed_login_attempts || 0) + 1;
      let isActionLocked = false;
      if (user.failed_login_attempts >= 5) {
        user.lockout_until = new Date(Date.now() + 15 * 60 * 1000).toISOString();
        isActionLocked = true;
      }
      await DbRepo.updateUser(user);
      await logAction(normalizedEmail, "SECURITY_FAILED", `Failed login password challenge. Attempt count: ${user.failed_login_attempts}`);

      if (isActionLocked) {
        return res.status(403).json({ 
          error: "Incorrect password. 5 consecutive failures detected. Account locked out for 15 minutes." 
        });
      } else {
        return res.status(401).json({ 
          error: `Incorrect password. ${5 - user.failed_login_attempts} remaining attempts before lock.` 
        });
      }
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/auth/logout", async (req, res) => {
  try {
    const token = req.cookies.token || (req.headers.authorization && req.headers.authorization.startsWith("Bearer ") ? req.headers.authorization.split(" ")[1] : "");
    if (token) {
      await DbRepo.deleteUserSessionByToken(token);
    }
    res.clearCookie("token", {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict"
    });
    return res.json({ success: true, message: "Logged out successfully" });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/auth/session", async (req, res) => {
  try {
    const token = req.cookies.token || (req.headers.authorization && req.headers.authorization.startsWith("Bearer ") ? req.headers.authorization.split(" ")[1] : "");
    if (!token) {
      return res.json({ isAuthenticated: false });
    }
    const session = await DbRepo.getUserSessionByToken(token);
    if (!session) {
      return res.json({ isAuthenticated: false });
    }
    return res.json({
      isAuthenticated: true,
      user: {
        id: session.user_id,
        email: session.email,
        role: session.role,
        beneficiaryId: session.beneficiary_id || null
      }
    });
  } catch (err: any) {
    res.json({ isAuthenticated: false, error: err.message });
  }
});

app.post("/api/auth/forgot-password", async (req, res) => {
  try {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Email is required" });
    }
    const normalizedEmail = email.toLowerCase().trim();
    const user = await DbRepo.getUserByEmail(normalizedEmail);
    if (!user) {
      // Secure response to prevent user discovery enumerations
      return res.json({ 
        success: true, 
        message: "If the email is registered in our database, a password reset link has been dispatched." 
      });
    }

    const resetToken = crypto.randomBytes(32).toString("hex");
    const resetExpires = new Date(Date.now() + 60 * 60 * 1000).toISOString(); // 1 hour expiry
    
    user.reset_token = resetToken;
    user.reset_token_expires = resetExpires;
    await DbRepo.updateUser(user);

    // Dynamic reset links
    const resetLink = `http://localhost:3000/reset-password?token=${resetToken}`;
    console.log(`[SECURITY] Forgot password requested for ${normalizedEmail}. Code: ${resetToken}. Link: ${resetLink}`);
    
    // Attempt real notification dispatch
    try {
      await EmailService.sendEmail({
        recipient: normalizedEmail,
        subject: "IDEAS-TVET Password Recovery Assistance",
        body: `
          <div style="font-family: sans-serif; max-width: 600px; padding: 20px; border: 1px solid #e1e1e1; border-radius: 8px;">
            <h2 style="color: #2b3e50;">Password Reset Authorization</h2>
            <p>You requested a password reset on your IDEAS-TVET account.</p>
            <p>Click the link below securely to authorize your password recovery:</p>
            <p style="margin: 25px 0;">
              <a href="${resetLink}" style="background-color: #248bf5; color: white; padding: 12px 24px; border-radius: 4px; text-decoration: none; font-weight: bold; display: inline-block;">Change Password</a>
            </p>
            <p style="font-size: 13px; color: #666;">This recovery link expires in 60 minutes. If you did not make this request, ignore this notification.</p>
          </div>
        `
      });
    } catch (mailErr: any) {
      console.log("[SECURITY] Mail dispatch failed (Resend not verified):", mailErr.message);
    }

    return res.json({ 
      success: true, 
      message: "If the email is registered, a password reset link has been dispatched.",
      token: resetToken // Included for instant integration testing
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/auth/reset-password", async (req, res) => {
  try {
    const { token, password } = req.body;
    if (!token || !password) {
      return res.status(400).json({ error: "Token and password are required" });
    }
    const user = await DbRepo.getUserByResetToken(token);
    if (!user) {
      return res.status(400).json({ error: "Invalid or expired password reset authorization." });
    }

    user.password_hash = bcrypt.hashSync(password, 10);
    user.reset_token = null;
    user.reset_token_expires = null;
    user.failed_login_attempts = 0;
    user.lockout_until = null;
    await DbRepo.updateUser(user);

    await logAction(user.email, "SECURITY_PASSWORD_RESET", "Password successfully recovered and changed.");

    return res.json({ success: true, message: "Your account password has been updated securely. You may log in." });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/auth/change-password", requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const { oldPassword, newPassword } = req.body;
    if (!oldPassword || !newPassword) {
      return res.status(400).json({ error: "Old password and new password are required" });
    }
    const user = await DbRepo.getUserByEmail(req.user!.email);
    if (!user) {
      return res.status(401).json({ error: "User profile context not found." });
    }

    const isMatched = bcrypt.compareSync(oldPassword, user.password_hash);
    if (!isMatched) {
      return res.status(400).json({ error: "Incorrect current password validation failed." });
    }

    user.password_hash = bcrypt.hashSync(newPassword, 10);
    user.failed_login_attempts = 0;
    user.lockout_until = null;
    await DbRepo.updateUser(user);

    await logAction(user.email, "SECURITY_PASSWORD_CHANGED", "Credentials manually updated and authenticated from settings.");

    return res.json({ success: true, message: "Password updated successfully." });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Admissions Workflow Integration endpoints
app.get("/api/email/health", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), (req, res) => {
  res.json({
    provider: "resend",
    configured: !!process.env.RESEND_API_KEY
  });
});

app.post("/api/email/test", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req, res) => {
  try {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Recipient email parameter 'email' is required." });
    }

    const auditOutcome = await EmailService.executeLiveIntegrationAudit(email);

    if (auditOutcome.deliveryStatus === "failed") {
      return res.status(400).json({
        messageId: auditOutcome.messageId,
        apiResponse: auditOutcome.apiResponse,
        deliveryStatus: auditOutcome.deliveryStatus,
        timestamp: auditOutcome.timestamp,
        errorDetails: auditOutcome.errorDetails,
        details: auditOutcome.details
      });
    }

    return res.status(200).json({
      messageId: auditOutcome.messageId,
      apiResponse: auditOutcome.apiResponse,
      deliveryStatus: auditOutcome.deliveryStatus,
      timestamp: auditOutcome.timestamp
    });

  } catch (err: any) {
    console.error("[POST /api/email/test] Integration route error:", err);
    return res.status(500).json({
      messageId: null,
      apiResponse: null,
      deliveryStatus: "failed",
      timestamp: new Date().toISOString(),
      errorDetails: {
        message: err.message || String(err),
        statusCode: 500,
        responseBody: err
      }
    });
  }
});

app.post("/api/email/production-test", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req, res) => {
  try {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ error: "Recipient email parameter 'email' is required." });
    }

    // Call updated live integration audit method using verified domain
    const auditOutcome = await EmailService.executeLiveIntegrationAudit(email);

    return res.status(auditOutcome.deliveryStatus === "success" ? 200 : 400).json({
      success: auditOutcome.deliveryStatus === "success",
      recipient: email,
      messageId: auditOutcome.messageId || "",
      provider: "resend"
    });
  } catch (err: any) {
    console.error("[POST /api/email/production-test] Unexpected route error:", err);
    return res.status(500).json({
      success: false,
      recipient: req.body?.email || "unknown",
      messageId: "",
      provider: "resend",
      error: err.message || String(err)
    });
  }
});

app.get("/api/admissions/email-health", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), AdmissionController.getEmailHealth);
app.post("/api/admissions/send-offer", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), AdmissionController.sendOffer);
app.get("/api/admissions/validate-token", AdmissionController.validateToken);
app.get("/api/admissions/secure-link", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), AdmissionController.getSecureLink);
app.post("/api/admissions/submit-response", AdmissionController.submitResponse);
function isValidTransition(oldStatus: string | undefined, newStatus: string): boolean {
  if (oldStatus === newStatus) return true;
  
  // Normalizing states:
  // "Acceptance Uploaded" -> Submitted
  // "Under Review" -> Under Review
  // "Accepted" -> Approved
  // "Acceptance Rejected" -> Rejected

  if (!oldStatus || ["Draft", "Pending", "Admission Generated", "Admission Sent", "Offer Viewed", "Acceptance Pending"].includes(oldStatus)) {
    return true;
  }

  if (oldStatus === "Acceptance Uploaded") {
    return ["Under Review", "Accepted", "Acceptance Rejected"].includes(newStatus);
  }

  if (oldStatus === "Under Review") {
    return ["Accepted", "Acceptance Rejected"].includes(newStatus);
  }

  if (oldStatus === "Accepted") {
    return ["Under Review"].includes(newStatus);
  }

  if (oldStatus === "Acceptance Rejected") {
    return ["Under Review"].includes(newStatus);
  }

  return true; // Default fallback for administrative updates
}

app.post("/api/admissions/transition-status", requireAuth, requireRole(["SUPER_ADMIN", "REVIEW_OFFICER", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { beneficiaryId, newStatus, reason, isUndo } = req.body;
    if (!beneficiaryId || !newStatus) {
      return res.status(400).json({ error: "Missing required parameters: beneficiaryId and newStatus" });
    }

    const beneficiary = await DbRepo.getBeneficiaryById(beneficiaryId);
    if (!beneficiary) {
      return res.status(404).json({ error: "Beneficiary not found" });
    }

    const oldStatus = beneficiary.admissionStatus || "Pending";

    // Enforce validation bounds unless it is an administrative undo bypassing
    if (!isUndo && !isValidTransition(oldStatus, newStatus)) {
      return res.status(400).json({ 
        error: `Invalid transition from status '${oldStatus}' to '${newStatus}'. This action is blocked by enterprise admission guidelines.` 
      });
    }

    const operatorEmail = req.user!.email;
    const operatorId = req.user!.id;
    let updatedBeneficiary: Beneficiary;

    if (newStatus === "Accepted") {
      updatedBeneficiary = await AdmissionService.approveAcceptance(beneficiaryId, operatorEmail);
    } else if (newStatus === "Acceptance Rejected") {
      updatedBeneficiary = await AdmissionService.rejectAcceptance(beneficiaryId, operatorEmail, reason || "No reason specified");
    } else if (newStatus === "Under Review") {
      beneficiary.admissionStatus = "Under Review";
      
      // If we are revoking approval, we should also reset verification status to PENDING_PHOTO for back-comp
      beneficiary.status = ProgramStatus.PENDING_PHOTO;
      beneficiary.updatedAt = new Date().toISOString();
      await DbRepo.upsertBeneficiary(beneficiary);
      updatedBeneficiary = beneficiary;

      // Log to Workflow History
      try {
        await DbRepo.saveWorkflowHistory({
          beneficiaryId,
          oldStatus,
          newStatus: "Under Review",
          changedBy: operatorEmail,
          changedAt: new Date().toISOString(),
          remarks: reason || "Manual status revocation to Under Review."
        });
      } catch (err) {}
    } else if (isUndo) {
      // Direct restoration
      beneficiary.admissionStatus = newStatus;
      if (newStatus === "Accepted") {
        beneficiary.status = ProgramStatus.VERIFIED;
      } else {
        beneficiary.status = ProgramStatus.PENDING_PHOTO;
      }
      beneficiary.updatedAt = new Date().toISOString();
      await DbRepo.upsertBeneficiary(beneficiary);
      updatedBeneficiary = beneficiary;

      // Log to Workflow History
      try {
        await DbRepo.saveWorkflowHistory({
          beneficiaryId,
          oldStatus,
          newStatus,
          changedBy: operatorEmail,
          changedAt: new Date().toISOString(),
          remarks: reason || "Administrative undo status restoration."
        });
      } catch (err) {}
    } else {
      return res.status(400).json({ error: `Unsupported state transition option: ${newStatus}` });
    }

    // Capture the transition or undo audit log securely
    const auditAction = isUndo ? "ACCEPTANCE_UNDO" : "ACCEPTANCE_TRANSITION";
    const auditMsg = isUndo 
      ? `Operator undone status transition. Reverted Trainee '${updatedBeneficiary.firstName} ${updatedBeneficiary.lastName}' (ID: ${updatedBeneficiary.id}) back to '${newStatus}'.`
      : `Transitioned verification status of Trainee '${updatedBeneficiary.firstName} ${updatedBeneficiary.lastName}' (ID: ${updatedBeneficiary.id}) from '${oldStatus}' to '${newStatus}'. Reason: ${reason || "None"}.`;

    const newLog: AuditLog = {
      id: "log_" + Date.now() + "_" + Math.floor(Math.random() * 1000),
      timestamp: new Date().toISOString(),
      username: operatorEmail,
      role: req.user!.role,
      action: auditAction,
      details: `Transition details - User ID: ${operatorId}, Email: ${operatorEmail}, Previous: ${oldStatus}, New: ${newStatus}, Timestamp: ${new Date().toISOString()}, Reason: ${reason || "None"}. ${auditMsg}`
    };
    await DbRepo.saveAuditLog(newLog);

    return res.status(200).json({ success: true, beneficiary: updatedBeneficiary });
  } catch (err: any) {
    console.error("[Transition status API Route failed]:", err);
    return res.status(500).json({ error: err.message || "Could not execute requested state transition." });
  }
});

app.post("/api/admissions/approve-acceptance", requireAuth, requireRole(["SUPER_ADMIN", "REVIEW_OFFICER"]), AdmissionController.approveAcceptance);
app.post("/api/admissions/reject-acceptance", requireAuth, requireRole(["SUPER_ADMIN", "REVIEW_OFFICER"]), AdmissionController.rejectAcceptance);

// PDF Download Endpoint with application/pdf and .pdf extension
app.get("/api/admissions/download-letter/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const beneficiary = await DbRepo.getBeneficiaryById(id);
    if (!beneficiary) {
      return res.status(404).send("Beneficiary candidate not found");
    }

    const pdfBuffer = await PdfService.generateAdmissionLetterPdf(beneficiary);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=Admission_Letter_${beneficiary.id}.pdf`);
    return res.status(200).send(pdfBuffer);
  } catch (e: any) {
    console.error("[GET /api/admissions/download-letter] Error compiling PDF document:", e);
    return res.status(500).send(e.message);
  }
});

// Unified PDF and MS Word Document Generator Download Endpoint
app.get("/api/documents/download/:id/:type", async (req, res) => {
  try {
    const { id, type } = req.params;
    const format = req.query.format || "pdf"; // "pdf" or "word"

    const beneficiary = await DbRepo.getBeneficiaryById(id);
    if (!beneficiary) {
      return res.status(404).send("Beneficiary candidate not found");
    }

    const settings = await DbRepo.getOrganizationSettings();
    const prefix = type === "certificate" ? "TVET-CRT" : type === "enrollment" ? "TVET-ENR" : type === "admission" ? "TVET-ADM" : type === "acceptance" ? "TVET-ACC" : "TVET-FRM";
    const verificationCode = `${prefix}-${id.split("-").pop() || "VAL"}`;
    const meta = {
      watermarkText: settings.watermarkText || "SECURED REGISTRY DOCUMENT",
      watermarkEnabled: !!settings.watermarkEnabled,
      verificationCode
    };

    const returnHtml = format === "word";
    let data: any;

    if (type === "admission") {
      data = await PdfService.generateAdmissionLetterPdf(beneficiary, meta, returnHtml);
    } else if (type === "acceptance") {
      data = await PdfService.generateAcceptanceLetterPdf(beneficiary, meta, returnHtml);
    } else if (type === "enrollment") {
      data = await PdfService.generateEnrollmentConfirmationPdf(beneficiary, meta, returnHtml);
    } else if (type === "certificate") {
      data = await PdfService.generateCompletionCertificatePdf(beneficiary, meta, returnHtml);
    } else if (type === "form") {
      data = await PdfService.generateAdmissionFormPdf(beneficiary, meta, returnHtml);
    } else {
      return res.status(400).send("Invalid document type");
    }

    if (format === "word") {
      res.setHeader("Content-Type", "application/msword");
      res.setHeader("Content-Disposition", `attachment; filename=${type}_${beneficiary.id}.doc`);
      return res.status(200).send(data);
    } else {
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename=${type}_${beneficiary.id}.pdf`);
      return res.status(200).send(data);
    }
  } catch (e: any) {
    console.error(`[GET /api/documents/download] Error compiling document:`, e);
    return res.status(500).send(e.message);
  }
});

// Custom Field Builder API
app.get("/api/custom-fields", requireAuth, async (req, res) => {
  try {
    const customFields = await DbRepo.getCustomFields();
    res.json(customFields);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.post("/api/custom-fields", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { label, type, required, options } = req.body;
    if (!label || !type) {
      return res.status(400).json({ error: "Label and field type are required" });
    }

    const name = label.toLowerCase().replace(/[^a-z0-9]/g, "");
    const newField: CustomField = {
      id: "cf_" + Date.now(),
      name,
      label,
      type,
      required: !!required,
      options: options || []
    };

    await DbRepo.saveCustomField(newField);
    await logAction(req.user!.email, "FIELD_CREATE", `Added dynamic custom field '${label}'`);
    res.status(201).json(newField);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.delete("/api/custom-fields/:id", requireAuth, requireRole(["SUPER_ADMIN"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { id } = req.params;
    const customFields = await DbRepo.getCustomFields();
    const index = customFields.findIndex(f => f.id === id);
    if (index !== -1) {
      const deletedField = customFields[index];
      await DbRepo.deleteCustomField(id);
      await logAction(req.user!.email, "FIELD_DELETE", `Removed dynamic custom field '${deletedField.label}'`);
      return res.json({ success: true, removed: deletedField });
    }
    res.status(404).json({ error: "Field not found" });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Organization settings resources (Phase 1)
app.get("/api/organization-settings", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req, res) => {
  try {
    const settings = await DbRepo.getOrganizationSettings();
    res.json(settings);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.put("/api/organization-settings", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const settings = req.body;
    await DbRepo.updateOrganizationSettings(settings);
    await logAction(req.user!.email, "SETTINGS_UPDATE", `Updated organization setting for ${settings.organizationName}`);
    res.json({ success: true, settings });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Training programs / batches resources
app.get("/api/training-programs", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req, res) => {
  try {
    const programs = await DbRepo.getTrainingPrograms();
    res.json(programs);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.post("/api/training-programs", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const program = req.body;
    if (!program.id) {
      program.id = "prog_" + Date.now();
    }
    await DbRepo.saveTrainingProgram(program);
    await logAction(req.user!.email, "PROGRAM_CREATE", `Created/Updated training program '${program.name}'`);
    res.status(201).json({ success: true, program });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.delete("/api/training-programs/:id", requireAuth, requireRole(["SUPER_ADMIN"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { id } = req.params;
    await DbRepo.deleteTrainingProgram(id);
    await logAction(req.user!.email, "PROGRAM_DELETE", `Removed training program id: ${id}`);
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Cloudinary Asset Upload proxied endpoint
app.post("/api/upload-asset", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { fileContent, fileName, folder } = req.body;
    if (!fileContent) {
      return res.status(400).json({ error: "Missing required upload parameter: fileContent" });
    }
    const secureUrl = await CloudinaryService.uploadDocument(fileContent, fileName || "asset_image", folder || "ideas_assets");
    res.json({ secureUrl });
  } catch (e: any) {
    console.error("[Upload Endpoint] Failed:", e);
    res.status(500).json({ error: e.message || "Failed uploading asset" });
  }
});

// Beneficiary management resource
app.get("/api/beneficiaries", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER", "REVIEW_OFFICER"]), async (req, res) => {
  try {
    const beneficiaries = await DbRepo.getBeneficiaries();
    res.json(beneficiaries);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.get("/api/beneficiaries/:id", requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const { id } = req.params;
    
    // In-depth Authorization boundary: Trainees are locked out of other beneficiaries profiles
    if (req.user!.role === "TRAINEE" && req.user!.beneficiaryId !== id) {
      return res.status(403).json({ error: "Access Denied. A trainee candidate can only access their personal profile." });
    }

    const b = await DbRepo.getBeneficiaryById(id);
    if (b) {
      res.json(b);
    } else {
      res.status(404).json({ error: "Beneficiary record not found" });
    }
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.post("/api/beneficiaries", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const data = req.body;
    if (!data.firstName || !data.lastName || !data.nin || !data.bvn) {
      return res.status(400).json({ error: "First Name, Last Name, NIN, and BVN are required fields" });
    }

    // Generate customized concurrent-safe sequential ID atomically
    const enrollYear = new Date().getFullYear();
    const id = await DbRepo.selectNextBeneficiaryId(enrollYear);

    const newBeneficiary: Beneficiary = {
      id,
      photo: data.photo || "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200",
      firstName: data.firstName,
      lastName: data.lastName,
      otherName: data.otherName || "",
      gender: data.gender || Gender.OTHER,
      bvn: data.bvn,
      nin: data.nin,
      state: data.state || "Imo",
      city: data.city || "Owerri",
      phoneNumber: data.phoneNumber || "",
      email: data.email || "",
      residentialAddress: data.residentialAddress || "",
      batch: data.batch || `Batch ${new Date().getFullYear()}-C`,
      customFields: data.customFields || {},
      tsp: "Unique Technology Nig. Ltd",
      program: "IDEAS-TVET",
      skillSector: "Computer Hardware and Cell Phone Repairs",
      status: data.status || ProgramStatus.DRAFT,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      guardianName: data.guardianName || "",
      guardianAddress: data.guardianAddress || "",
      guardianPhone: data.guardianPhone || "",
      physicalChallenge: data.physicalChallenge || "",
      bankAccountHolder: data.bankAccountHolder || "",
      bankName: data.bankName || "",
      bankSortCode: data.bankSortCode || "",
      bankAccountNumber: data.bankAccountNumber || "",
      educationQualification: data.educationQualification || "",
      dateOfBirth: data.dateOfBirth || ""
    };

    await DbRepo.upsertBeneficiary(newBeneficiary);
    
    // Also record the initial state into workflow_history (Phase 1)
    await DbRepo.saveWorkflowHistory({
      beneficiaryId: newBeneficiary.id,
      oldStatus: "null",
      newStatus: newBeneficiary.status,
      changedBy: req.user!.email,
      changedAt: new Date().toISOString(),
      remarks: data.remarks || "Registered / Enrolled into Gov Portal"
    });

    await logAction(req.user!.email, "BENEFICIARY_CREATE", `Registered beneficiary ${newBeneficiary.firstName} ${newBeneficiary.lastName} with ID ${newBeneficiary.id}`);
    res.status(201).json(newBeneficiary);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.put("/api/beneficiaries/:id", requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const { id } = req.params;

    // Security Gate check
    if (req.user!.role === "TRAINEE" && req.user!.beneficiaryId !== id) {
      return res.status(403).json({ error: "Access Denied. You are forbidden from modifying other candidate profiles." });
    }
    if (req.user!.role !== "TRAINEE" && !["SUPER_ADMIN", "ADMIN_OFFICER"].includes(req.user!.role)) {
      return res.status(403).json({ error: "Access Denied. Permissions restricted to Super Admins and Admin Officers." });
    }

    const original = await DbRepo.getBeneficiaryById(id);
    if (original) {
      const data = req.body;
      
      if (data.admissionStatus && data.admissionStatus !== original.admissionStatus) {
        if (!isValidTransition(original.admissionStatus, data.admissionStatus)) {
          return res.status(400).json({ 
            error: `Invalid status transition from '${original.admissionStatus || "Pending"}' to '${data.admissionStatus}'. This transition is blocked by workflow rules.` 
          });
        }
        
        const operatorEmail = req.user!.email;
        const operatorId = req.user!.id;
        const newLog: AuditLog = {
          id: "log_" + Date.now() + "_" + Math.floor(Math.random() * 1000),
          timestamp: new Date().toISOString(),
          username: operatorEmail,
          role: req.user!.role,
          action: "ACCEPTANCE_TRANSITION",
          details: `Transition details - User ID: ${operatorId}, Email: ${operatorEmail}, Previous: ${original.admissionStatus || "Pending"}, New: ${data.admissionStatus}, Timestamp: ${new Date().toISOString()}, Reason: Direct profile modification.`
        };
        await DbRepo.saveAuditLog(newLog);
      }

      const isStatusChanging = data.status && data.status !== original.status;
      const oldStatusVal = original.status || "PENDING";
      const newStatusVal = data.status;

      const updated: Beneficiary = {
        ...original,
        ...data,
        id: original.id, // Cannot change ID
        updatedAt: new Date().toISOString()
      };
      
      await DbRepo.upsertBeneficiary(updated);

      // Record workflow history if the status changed (Phase 1)
      if (isStatusChanging) {
        await DbRepo.saveWorkflowHistory({
          beneficiaryId: id,
          oldStatus: oldStatusVal,
          newStatus: newStatusVal,
          changedBy: req.user!.email,
          changedAt: new Date().toISOString(),
          remarks: data.remarks || `Status updated from ${oldStatusVal} to ${newStatusVal}`
        });

        // Trigger automatic document generation asynchronously (Phase 3)
        // This is non-blocking so profile updates are fast and responsive
        autoGenerateDocuments(id, newStatusVal, req.user!.email).catch(e => {
          console.error(`[Auto-Gen] Background doc gen failed for ${id}:`, e);
        });
      }

      await logAction(req.user!.email, "BENEFICIARY_UPDATE", `Updated details of beneficiary ${original.firstName} ${original.lastName} (ID: ${original.id})`);
      return res.json(updated);
    }
    res.status(404).json({ error: "Beneficiary not found" });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.delete("/api/beneficiaries/:id", requireAuth, requireRole(["SUPER_ADMIN"]), async (req: AuthenticatedRequest, res) => {
  try {
    const target = await DbRepo.getBeneficiaryById(req.params.id);
    if (target) {
      await DbRepo.deleteBeneficiary(req.params.id);
      await logAction(req.user!.email, "BENEFICIARY_DELETE", `Soft deleted beneficiary registration ${target.firstName} ${target.lastName} (ID: ${target.id})`);
      return res.json({ success: true, deleted: target });
    }
    res.status(404).json({ error: "Beneficiary not found" });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// --- DOCUMENT AUTOMATION API ENDPOINTS ---

// Fetch generated document history for a beneficiary
app.get("/api/documents/:beneficiaryId/history", requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const history = await DocumentService.getDocumentHistory(req.params.beneficiaryId);
    res.json(history);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Fetch workflow status history timeline for a beneficiary
app.get("/api/beneficiaries/:id/workflow-history", requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const history = await DbRepo.getWorkflowHistory(req.params.id);
    res.json(history);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Generate or Regenerate a document
app.post("/api/documents/generate", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { beneficiaryId, documentType, regenerate } = req.body;
    if (!beneficiaryId || !documentType) {
      return res.status(400).json({ error: "beneficiaryId and documentType are required fields." });
    }

    const generatedBy = req.user?.email || "SYSTEM";
    let document;

    if (regenerate === true) {
      document = await DocumentService.regenerateDocument(beneficiaryId, documentType as DocumentType, generatedBy);
    } else {
      document = await DocumentService.generateDocument(beneficiaryId, documentType as DocumentType, generatedBy);
    }

    res.json({ success: true, document });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Dispatch a generated document to Email
app.post("/api/documents/email", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { documentId, recipientEmail } = req.body;
    if (!documentId) {
      return res.status(400).json({ error: "documentId is a required field." });
    }

    const outcome = await DocumentService.sendDocumentEmail(documentId, recipientEmail);
    res.json(outcome);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// Track document downloads and visual previews
app.post("/api/documents/track", async (req, res) => {
  try {
    const { documentId, beneficiaryId, deliveryType, recipient, sentBy, status } = req.body;
    if (!beneficiaryId || !deliveryType) {
      return res.status(400).json({ error: "beneficiaryId and deliveryType are required tracker keys." });
    }
    const sentByWho = sentBy || (req as any).user?.email || "System Portal";
    await DbRepo.saveDeliveryLog({
      documentId,
      beneficiaryId,
      deliveryType,
      recipient: recipient || "Trainee Portfolio",
      sentBy: sentByWho,
      status: status || "Logged Successfully"
    });
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Fetch delivery logs for a given beneficiary
app.get("/api/documents/delivery-logs/:beneficiaryId", requireAuth, async (req, res) => {
  try {
    const { beneficiaryId } = req.params;
    const logs = await DbRepo.getDeliveryLogs(beneficiaryId);
    res.json(logs);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Public Document Verification Endpoint
app.post("/api/documents/verify", async (req, res) => {
  try {
    const { code, id } = req.body;
    if (!code && !id) {
      return res.status(400).json({ error: "Please provide a verification code or document ID." });
    }

    let doc = null;
    if (code) {
      doc = await DbRepo.getGeneratedDocumentByCode(code);
    } else if (id) {
      doc = await DbRepo.getGeneratedDocumentById(id);
    }

    if (!doc) {
      return res.status(404).json({ error: "No matching official document found in registry database." });
    }

    // Get beneficiary name
    const beneficiary = await DbRepo.getBeneficiaryById(doc.beneficiaryId);
    const beneficiaryName = beneficiary 
      ? `${beneficiary.firstName} ${beneficiary.lastName}`
      : "Unknown Candidate";

    // Mark as verified upon lookup (to demonstrate active validation tracking)
    if (doc.verificationStatus !== "VERIFIED") {
      try {
        await DbRepo.updateGeneratedDocumentVerificationStatus(doc.id, "VERIFIED", new Date());
        doc.verificationStatus = "VERIFIED";
        doc.verificationDate = new Date().toISOString();
      } catch (err) {}
    }

    res.json({
      success: true,
      documentId: doc.id,
      beneficiaryId: doc.beneficiaryId,
      beneficiaryName,
      documentType: doc.documentType,
      version: doc.version,
      pdfUrl: doc.pdfUrl,
      verificationCode: doc.verificationCode,
      verificationStatus: doc.verificationStatus,
      verificationDate: doc.verificationDate || new Date().toISOString(),
      createdAt: doc.createdAt,
    });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// GET REST Dynamic Verification Endpoint by Code
app.get("/api/documents/verify/:verificationCode", async (req, res) => {
  try {
    const { verificationCode } = req.params;
    if (!verificationCode) {
      return res.status(400).json({ valid: false, error: "Verification code is required." });
    }

    const doc = await DbRepo.getGeneratedDocumentByCode(verificationCode);
    if (!doc) {
      return res.json({ valid: false });
    }

    // Lookup beneficiary for candidate name display
    const beneficiary = await DbRepo.getBeneficiaryById(doc.beneficiaryId);
    const beneficiaryName = beneficiary
      ? `${beneficiary.firstName} ${beneficiary.lastName}`
      : "Unknown Candidate";

    // Mark as verified upon lookup
    if (doc.verificationStatus !== "VERIFIED") {
      try {
        await DbRepo.updateGeneratedDocumentVerificationStatus(doc.id, "VERIFIED", new Date());
        doc.verificationStatus = "VERIFIED";
        doc.verificationDate = new Date().toISOString();
        doc.verifiedAt = new Date().toISOString();
      } catch (err) {}
    }

    // Return verification-safe fields only (Strict: No BVN, NIN, Phone, Email)
    res.json({
      valid: true,
      document: {
        id: doc.id,
        beneficiaryId: doc.beneficiaryId,
        beneficiaryName,
        documentType: doc.documentType,
        version: doc.version,
        pdfUrl: doc.pdfUrl,
        verificationCode: doc.verificationCode,
        verificationStatus: doc.verificationStatus,
        verificationDate: doc.verificationDate || doc.verifiedAt || new Date().toISOString(),
        verifiedAt: doc.verifiedAt || doc.verificationDate || new Date().toISOString(),
        createdAt: doc.createdAt
      }
    });
  } catch (e: any) {
    res.status(500).json({ valid: false, error: e.message });
  }
});

// Audit Logging Fetch
app.get("/api/audit-logs", requireAuth, requireRole(["SUPER_ADMIN"]), async (req, res) => {
  try {
    const auditLogs = await DbRepo.getAuditLogs();
    res.json(auditLogs);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// CSV Export compilation endpoint
app.get("/api/export/csv", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER", "REVIEW_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const customFields = await DbRepo.getCustomFields();
    const beneficiaries = await DbRepo.getBeneficiaries();

    await logAction(req.user!.email, "EXCEL_EXPORT", "Triggered bulk beneficiary spreadsheet export in CSV format");

    // Compile header columns recursively including dynamic fields
    const headers = [
      "Beneficiary ID", "First Name", "Last Name", "Other Name", "Gender", "BVN", "NIN",
      "State", "City", "Phone Number", "Email", "Residential Address", "Batch",
      "TSP Provider", "Program Track", "Skill Sector", "Verification Status", "Lifecycle Stage"
    ];
    
    // Custom headers from customFields schema definition
    customFields.forEach(cf => {
      headers.push(`Custom: ${cf.label}`);
    });

    let csvContent = headers.join(",") + "\n";

    beneficiaries.forEach(b => {
      const row = [
        `"${b.id}"`, `"${b.firstName}"`, `"${b.lastName}"`, `"${b.otherName || ""}"`, `"${b.gender}"`, `"${b.bvn}"`, `"${b.nin}"`,
        `"${b.state}"`, `"${b.city}"`, `"${b.phoneNumber}"`, `"${b.email}"`, `"${b.residentialAddress.replace(/"/g, '""')}"`, `"${b.batch}"`,
        `"${b.tsp}"`, `"${b.program}"`, `"${b.skillSector}"`, `"${b.status}"`, `"${b.admissionStatus || "Draft"}"`
      ];

      customFields.forEach(cf => {
        row.push(`"${(b.customFields[cf.name] || "").replace(/"/g, '""')}"`);
      });

      csvContent += row.join(",") + "\n";
    });

    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", "attachment; filename=ideas_tvet_beneficiaries_export.csv");
    res.status(200).send(csvContent);
  } catch (e: any) {
    res.status(500).send(e.message);
  }
});

// Excel Spreadsheet compilation endpoint (.xls styled HTML)
app.get("/api/export/excel", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER", "REVIEW_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { state, batch } = req.query;
    const beneficiaries = await DbRepo.getBeneficiaries();

    await logAction(req.user!.email, "EXCEL_EXPORT", `Triggered bulk beneficiary spreadsheet export in Excel format for State: ${state}, Batch: ${batch}`);

    // Filter beneficiaries list matching the request
    const filtered = beneficiaries.filter(b => {
      const sMatch = !state || state === "all" || b.state === state;
      const bMatch = !batch || batch === "all" || b.batch === batch;
      return sMatch && bMatch;
    });

    // Construct standard Excel openable XML/HTML string with exact 10 columns
    let html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
  body { font-family: Arial, sans-serif; margin: 0; }
  table { border-collapse: collapse; width: 100%; }
  th { background-color: #312e81; color: #ffffff; font-weight: bold; border: 1px solid #cbd5e1; padding: 12px; font-size: 11px; text-transform: uppercase; }
  td { border: 1px solid #cbd5e1; padding: 10px; font-size: 11px; vertical-align: middle; }
  .title-cell { font-size: 16px; font-weight: bold; color: #1e1b4b; background-color: #f1f5f9; text-align: center; }
  .meta-cell { font-size: 11px; color: #64748b; background-color: #f1f5f9; text-align: center; }
  .photo-img { width: 50px; height: 50px; border-radius: 25px; border: 1px solid #e2e8f0; }
</style>
</head>
<body>
  <table>
    <tr>
      <td colspan="11" class="title-cell" height="40">IDEAS-TVET BENEFICIARY PHOTO ALBUM REGISTRY</td>
    </tr>
    <tr>
      <td colspan="11" class="meta-cell" height="25">Training Service Provider (TSP): Unique Technology Nig. Ltd | Date Extracted: ${new Date().toLocaleDateString("en-GB")}</td>
    </tr>
    <tr><td colspan="11" style="background-color:#ffffff; border:none;" height="15"></td></tr>
    <thead>
      <tr>
        <th>Photo</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>NIN</th>
        <th>BVN</th>
        <th>State</th>
        <th>City</th>
        <th>TSP</th>
        <th>Skill Sector</th>
        <th>Lifecycle Stage</th>
        <th>Registration Date</th>
      </tr>
    </thead>
    <tbody>
  `;

    filtered.forEach(b => {
      const photoUrl = b.photo;
      const formattedDate = b.createdAt ? new Date(b.createdAt).toLocaleDateString("en-GB") : "N/A";
      html += `
      <tr>
        <td align="center" valign="middle" height="60">
          <img class="photo-img" src="${photoUrl}" width="50" height="50" />
        </td>
        <td>${b.firstName}</td>
        <td>${b.lastName}</td>
        <td style="mso-number-format:'@';">${b.nin}</td>
        <td style="mso-number-format:'@';">${b.bvn}</td>
        <td>${b.state}</td>
        <td>${b.city}</td>
        <td>${b.tsp || "Unique Technology Nig. Ltd"}</td>
        <td>${b.skillSector || "Computer Hardware and Cell Phone Repairs"}</td>
        <td style="font-weight: bold; color: #312e81;">${b.admissionStatus || "Draft"}</td>
        <td>${formattedDate}</td>
      </tr>
    `;
    });

    if (filtered.length === 0) {
      html += `<tr><td colspan="11" align="center" style="font-weight:bold; color:#ef4444; padding:20px;">No beneficiary records found for the selected filter parameters.</td></tr>`;
    }

    html += `
    </tbody>
  </table>
</body>
</html>
  `;

    res.setHeader("Content-Type", "application/vnd.ms-excel");
    res.setHeader("Content-Disposition", "attachment; filename=ideas_tvet_beneficiaries_export.xls");
    res.status(200).send(html);
  } catch (e: any) {
    res.status(500).send(e.message);
  }
});

// PDF Exporter compilation endpoint (Renders beautiful media A4 printable document)
app.get("/api/export/pdf", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER", "REVIEW_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { state, batch } = req.query;
    const beneficiaries = await DbRepo.getBeneficiaries();
    const settings = await DbRepo.getOrganizationSettings();

    await logAction(req.user!.email, "PDF_EXPORT", `Triggered official multi-page registry-style PDF generation for State: ${state}, Batch: ${batch}`);

    const filtered = beneficiaries.filter(b => {
      const sMatch = !state || state === "all" || b.state === state;
      const bMatch = !batch || batch === "all" || b.batch === batch;
      return sMatch && bMatch;
    });

    let html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>IDEAS-TVET Official Beneficiary Photo Album Registry PDF</title>
  <style>
    @page {
      size: A4 portrait;
      margin: 20mm 15mm 20mm 15mm;
    }
    @media print {
      .print-button-container {
        display: none !important;
      }
      body {
        background: none;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      .document-page {
        margin: 0 !important;
        box-shadow: none !important;
        page-break-after: always;
        width: 100% !important;
        min-height: auto !important;
        padding: 0 !important;
      }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #1e293b;
      line-height: 1.5;
      margin: 0;
      padding: 0;
      background: #f1f5f9;
    }
    .print-button-container {
      background: #312e81;
      padding: 15px 30px;
      color: white;
      display: flex;
      justify-content: space-between;
      align-items: center;
      position: sticky;
      top: 0;
      z-index: 100;
      box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);
    }
    .btn {
      background-color: #22c55e;
      color: white;
      padding: 10px 20px;
      font-size: 13px;
      font-weight: 700;
      border: none;
      border-radius: 6px;
      cursor: pointer;
      text-transform: uppercase;
      box-shadow: 0 2px 4px rgba(0,0,0,0.15);
      transition: all 0.2s;
    }
    .btn:hover {
      background-color: #16a34a;
      transform: translateY(-1px);
    }
    .document-page {
      width: 210mm;
      min-height: 297mm;
      padding: 20mm;
      box-sizing: border-box;
      background: white;
      margin: 30px auto;
      box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);
      position: relative;
    }
    
    /* Repeating scale layout for print */
    .layout-table {
      width: 100%;
      border-collapse: collapse;
    }
    
    .header-spacer {
      height: 70px;
    }
    
    .footer-spacer {
      height: 50px;
    }
    
    .fixed-header {
      position: fixed;
      top: 0;
      left: 20mm;
      right: 20mm;
      height: 60px;
      border-bottom: 2px solid #312e81;
      display: flex;
      justify-content: space-between;
      align-items: center;
      z-index: 10;
      background-color: white;
    }
    .logo-section {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .logo-icon {
      width: 32px;
      height: 32px;
      background-color: #312e81;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
      font-size: 14px;
    }
    .logo-text h1 {
      margin: 0;
      font-size: 13px;
      font-weight: 700;
      text-transform: uppercase;
      color: #1e1b4b;
    }
    .logo-text p {
      margin: 0;
      font-size: 8px;
      color: #64748b;
      font-weight: bold;
      letter-spacing: 0.5px;
    }
    .doc-meta {
      text-align: right;
      font-size: 10px;
      color: #64748b;
    }
    .doc-meta strong {
      color: #1e293b;
    }
    
    .fixed-footer {
      position: fixed;
      bottom: 0;
      left: 20mm;
      right: 20mm;
      height: 40px;
      border-top: 1px dashed #cbd5e1;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 8px;
      color: #64748b;
      z-index: 10;
      background-color: white;
    }
    
    .title-block {
      text-align: center;
      margin-bottom: 25px;
      margin-top: 10px;
    }
    .title-block h2 {
      font-size: 18px;
      color: #0f172a;
      margin: 0 0 4px 0;
      text-transform: uppercase;
      letter-spacing: -0.5px;
    }
    .title-block p {
      font-size: 11px;
      color: #475569;
      margin: 0;
    }
    .intro-paragraph {
      font-size: 11px;
      line-height: 1.5;
      color: #334155;
      margin-bottom: 20px;
      text-align: justify;
    }
    
    .registry-container {
      width: 100%;
    }
    
    .record-block {
      width: 100%;
      border-collapse: collapse;
      border: 1.5px solid #475569;
      border-radius: 8px;
      margin-bottom: 20px;
      page-break-inside: avoid;
      background-color: #ffffff;
    }
    
    .photo-cell {
      width: 130px;
      padding: 12px;
      border-right: 1.5px solid #cbd5e1;
      text-align: center;
      vertical-align: middle;
      background-color: #f8fafc;
    }
    
    .photo-img {
      width: 105px;
      height: 135px;
      object-fit: contain;
      border: 1px solid #94a3b8;
      border-radius: 4px;
      display: block;
      margin: 0 auto;
    }
    
    .details-cell {
      padding: 12px 16px;
      vertical-align: top;
    }
    
    .details-header {
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 5px;
      margin-bottom: 8px;
    }
    
    .details-name {
      margin: 0;
      font-size: 13px;
      font-weight: 700;
      color: #1e1b4b;
      text-transform: uppercase;
    }
    
    .details-ref {
      font-family: monospace;
      font-size: 9px;
      color: #64748b;
      font-weight: bold;
    }
    
    .info-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 10.5px;
    }
    
    .info-table td {
      padding: 4px 0;
      border-bottom: 1px dashed #f1f5f9;
    }
    
    .info-label {
      width: 140px;
      font-weight: 600;
      color: #475569;
    }
    
    .info-value {
      font-weight: 700;
      color: #0f172a;
    }
    
    .sign-section {
      display: flex;
      justify-content: space-between;
      margin-top: 40px;
      padding-top: 15px;
      border-top: 1px dashed #cbd5e1;
      page-break-inside: avoid;
    }
    .sign-box {
      width: 45%;
      font-size: 10px;
    }
    .sign-line {
      border-bottom: 1px solid #94a3b8;
      height: 35px;
      margin-bottom: 6px;
    }
  </style>
</head>
<body>
  <div class="print-button-container">
    <div style="font-size: 13px;">
      <strong>Official Registry Document Compiler Active</strong> | Click 'Print' to save as dynamic vector PDF.
    </div>
    <button class="btn" onclick="window.print()">Print & Save PDF</button>
  </div>

  <div class="document-page">
    
    <!-- Fixed top header and footer for layout printing -->
    <div class="fixed-header">
      ${settings.photoAlbumHeaderUrl ? `
        <div style="height: 100%; display: flex; align-items: center; justify-content: flex-start; max-width: 60%; overflow: hidden;">
          <img src="${settings.photoAlbumHeaderUrl}" style="max-height: 50px; width: auto; max-width: 100%; object-fit: contain; display: block;" referrerPolicy="no-referrer" />
        </div>
      ` : `
        <div class="logo-section">
          <div class="logo-icon">U</div>
          <div class="logo-text">
            <h1>${settings.organizationName || "Unique Technology Nig. Ltd"}</h1>
            <p>IDEAS-TVET Program Registry</p>
          </div>
        </div>
      `}
      <div class="doc-meta">
        <div>Ref: <strong>TVET-ALBUM-RECON</strong></div>
        <div>Date: <strong>${new Date().toLocaleDateString("en-GB")}</strong></div>
        <div>Scope: <strong>National Security Code</strong></div>
      </div>
    </div>
    
    <div class="fixed-footer">
      <span>Security Hash Key: 0x8FE0A1959C - Classified Gov Registry</span>
      <span>Printed via IDEAS Portal Management System</span>
      <span>Page A4 Portrait Verified</span>
    </div>

    <table class="layout-table">
      <thead>
        <tr>
          <td>
            <div class="header-spacer"></div>
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div class="title-block">
              <h2>Official Beneficiary Photo Album Registry</h2>
              <p>Federally Authenticated TVET Trainees Profile Dashboard Directory</p>
            </div>

            <p class="intro-paragraph">
              This is to certify that the dynamic biometrics registration lock is active across our federal skill hubs. The candidates cataloged below are verified by our accredited audit workflows as enrolled participants for <strong>Computer Hardware and Cell Phone Repairs</strong>. All biometrics matching filters conform to TVET program standards.
            </p>

            <div class="registry-container">
              <table style="width: 100%; border-collapse: collapse; margin-top: 15px; border: 2px solid #000000;">
                <thead>
                  <tr style="background-color: #1e1b4b; color: white;">
                    <th style="border: 2px solid #000000; padding: 10px; text-align: center; width: 45px; font-weight: bold; font-size: 11px; text-transform: uppercase;">S/N</th>
                    <th style="border: 2px solid #000000; padding: 10px; text-align: center; width: 150px; font-weight: bold; font-size: 11px; text-transform: uppercase;">Photograph</th>
                    <th style="border: 2px solid #000000; padding: 10px; text-align: left; font-weight: bold; font-size: 11px; text-transform: uppercase;">Details</th>
                  </tr>
                </thead>
                <tbody>
    `;

    filtered.forEach((b, index) => {
      const lga = b.customFields?.["Local Government Area (LGA)"] || b.customFields?.["lga"] || b.customFields?.["LGA"] || b.customFields?.["cf_lga"] || "N/A";
      const age = b.customFields?.["Age"] || b.customFields?.["age"] || b.customFields?.["Date of Birth"] || b.customFields?.["dob"] || "N/A";
      
      html += `
                  <tr style="page-break-inside: avoid; break-inside: avoid;">
                    <td style="border: 1.5px solid #000000; padding: 12px; text-align: center; font-weight: bold; font-family: monospace; font-size: 11px; vertical-align: middle; color: #1e293b; background-color: #ffffff;">
                      ${index + 1}
                    </td>
                    <td style="border: 1.5px solid #000000; padding: 12px; text-align: center; vertical-align: middle; background-color: #ffffff;">
                      <div style="font-weight: bold; font-size: 8.5pt; text-transform: uppercase; margin-bottom: 6px; color: #1e1b4b; font-family: sans-serif;">Photograph</div>
                      <div style="width: 100px; height: 120px; background: #ffffff; border: 1.5px solid #000000; display: flex; align-items: center; justify-content: center; margin: 0 auto; overflow: hidden; box-sizing: border-box;">
                        ${b.photo ? `
                          <img src="${b.photo}" alt="Passport" referrerPolicy="no-referrer" style="width: 100px; height: 120px; object-fit: cover;" />
                        ` : `
                          <span style="font-size: 8px; font-weight: bold; color: #94a3b8; font-family: monospace; padding: 5px; text-align: center;">NO PHOTO AVAILABLE</span>
                        `}
                      </div>
                      <div style="margin-top: 6px; font-family: monospace; font-size: 8.5px; font-weight: bold; color: #64748b;">REF: ${b.id}</div>
                    </td>
                    <td style="border: 1.5px solid #000000; padding: 15px; vertical-align: top; background-color: #ffffff;">
                      <div style="font-weight: bold; font-size: 8.5pt; text-transform: uppercase; margin-bottom: 6px; color: #1e1b4b; font-family: sans-serif;">Details</div>
                      <table style="width: 100%; border-collapse: collapse; font-family: monospace; font-size: 11px;">
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">Full Name:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a; text-transform: uppercase;">${b.lastName}, ${b.firstName} ${b.otherName || ""}</td>
                        </tr>
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">Gender:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a; text-transform: uppercase;">${b.gender}</td>
                        </tr>
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">Age / Date of Birth:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a;">${age}</td>
                        </tr>
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">Phone Number:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a;">${b.phoneNumber || "N/A"}</td>
                        </tr>
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">NIN:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a;">${b.nin || "N/A"}</td>
                        </tr>
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">Email Address:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a;">${b.email || "N/A"}</td>
                        </tr>
                        <tr style="border-bottom: 1px dashed #cccccc;">
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">State of Origin:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #0f172a;">${b.state || "N/A"}</td>
                        </tr>
                        <tr>
                          <td style="padding: 5px 0; width: 180px; font-weight: bold; color: #475569; text-transform: uppercase; font-size: 9px;">Local Government Area:</td>
                          <td style="padding: 5px 0; font-weight: bold; color: #1e1b4b;">${lga}</td>
                        </tr>
                      </table>
                    </td>
                  </tr>
      `;
    });

    html += `
                </tbody>
              </table>
    `;

    if (filtered.length === 0) {
      html += `
      <div style="text-align: center; color: #ef4444; font-weight: bold; border: 1.5px dashed #ef4444; padding: 30px; border-radius: 8px; margin-top: 20px;">
        No verified candidates found matching filtered criteria.
      </div>
      `;
    }

    html += `
            </div>

            <div class="sign-section">
              <div class="sign-box">
                <div class="sign-line"></div>
                <strong>Accredited Coordinator Sign-off</strong>
                <p style="margin: 3px 0; color: #64748b; font-size: 9px;">Unique Technology Nig. Ltd Coordinator</p>
              </div>
              <div class="sign-box" style="text-align: right;">
                <div class="sign-line"></div>
                <strong>Federal Board Auditor Signature</strong>
                <p style="margin: 3px 0; color: #64748b; font-size: 9px;">Federal Ministry of Education Officer</p>
              </div>
            </div>
          </td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td>
            <div class="footer-spacer"></div>
          </td>
        </tr>
      </tfoot>
    </table>

  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 800);
    };
  </script>
</body>
</html>
    `;

    res.setHeader("Content-Type", "text/html");
    res.status(200).send(html);
  } catch (e: any) {
    res.status(500).send(e.message);
  }
});

// Official Microsoft Word Exporter Endpoint
app.get("/api/export/word", requireAuth, requireRole(["SUPER_ADMIN", "ADMIN_OFFICER", "REVIEW_OFFICER"]), async (req: AuthenticatedRequest, res) => {
  try {
    const { state, batch } = req.query;
    const beneficiaries = await DbRepo.getBeneficiaries();
    const settings = await DbRepo.getOrganizationSettings();

    await logAction(req.user!.email, "WORD_EXPORT", `Triggered official registry-style MSG-Word generation for State: ${state}, Batch: ${batch}`);

    const filtered = beneficiaries.filter(b => {
      const sMatch = !state || state === "all" || b.state === state;
      const bMatch = !batch || batch === "all" || b.batch === batch;
      return sMatch && bMatch;
    });

    let html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8">
  <title>IDEAS-TVET Official Beneficiary Photo Album Registry</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotOptimizeForBrowser/>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #1e293b;
      line-height: 1.4;
    }
    .header-table {
      width: 100%;
      border-bottom: 2pt solid #000000;
      margin-bottom: 20pt;
      padding-bottom: 10pt;
    }
    .title-block {
      text-align: center;
      margin: 15pt 0;
    }
    .title-block h2 {
      font-size: 16pt;
      color: #0f172a;
      text-transform: uppercase;
      margin: 0;
    }
    .title-block p {
      font-size: 10pt;
      color: #475569;
      margin: 2pt 0;
    }
    .intro-paragraph {
      font-size: 10pt;
      color: #334155;
      margin-bottom: 20pt;
    }
    .record-block {
      width: 100%;
      border: 1px solid #000000;
      margin-bottom: 25pt;
      border-collapse: collapse;
    }
    .photo-cell {
      width: 110pt;
      padding: 10pt;
      border-right: 1.5pt solid #000000;
      text-align: center;
      vertical-align: middle;
      background-color: #f8fafc;
    }
    .photo-img {
      width: 90pt;
      height: 120pt;
      border: 1.5pt solid #000000;
    }
    .details-cell {
      padding: 10pt;
      vertical-align: top;
    }
    .details-header {
      border-bottom: 1.5pt solid #000000;
      padding-bottom: 5pt;
      margin-bottom: 8pt;
    }
    .details-name {
      margin: 0;
      font-size: 12pt;
      font-weight: bold;
      color: #000000;
      text-transform: uppercase;
    }
    .details-ref {
      font-family: Arial, sans-serif;
      font-size: 8.5pt;
      color: #64748b;
    }
    .sign-table {
      width: 100%;
      margin-top: 30pt;
      border-top: 1.5pt solid #000000;
      padding-top: 10pt;
    }
    .sign-box {
      width: 50%;
      font-size: 9pt;
    }
  </style>
</head>
<body style="tab-interval:.5in">
  <div class="Section1">
    ${settings.photoAlbumHeaderUrl ? `
    <table class="header-table" style="width: 100%; border-collapse: collapse; border-bottom: 2pt solid #000000; margin-bottom: 20pt; padding-bottom: 10pt;">
      <tr>
        <td style="text-align: center; vertical-align: middle;">
          <img src="${settings.photoAlbumHeaderUrl}" style="max-height: 80px; width: auto; max-width: 100%;" />
        </td>
      </tr>
    </table>
    ` : `
    <table class="header-table" style="width: 100%; border-collapse: collapse;">
      <tr>
        <td style="width: 33%; text-align: left; vertical-align: middle;">
          ${settings.fmeLogoUrl ? `<img src="${settings.fmeLogoUrl}" width="65" height="65" style="width:65px;height:65px;" />` : `<h3 style="margin:0; font-size:10pt;">FEDERAL EDUCATION</h3>`}
        </td>
        <td style="width: 34%; text-align: center; vertical-align: middle;">
          ${settings.ideasLogoUrl ? `<img src="${settings.ideasLogoUrl}" width="75" height="65" style="width:75px;height:65px;" />` : `<h2 style="margin:0; font-size:12pt; color:#1e1b4b;">IDEAS-TVET INITIATIVE</h2>`}
        </td>
        <td style="width: 33%; text-align: right; vertical-align: middle;">
          ${settings.worldBankLogoUrl ? `<img src="${settings.worldBankLogoUrl}" width="65" height="65" style="width:65px;height:65px;" />` : `<h3 style="margin:0; font-size:10pt;">WORLD BANK</h3>`}
        </td>
      </tr>
    </table>
    `}

    <div class="title-block">
      <h2>Official Beneficiary Photo Album Registry</h2>
      <p>Federally Authenticated TVET Trainees Profile Dashboard Directory</p>
    </div>

    <p class="intro-paragraph">
      This is to certify that the dynamic biometrics registration lock is active across our federal skill hubs. The candidates cataloged below are verified by our accredited audit workflows as enrolled participants for <strong>Computer Hardware and Cell Phone Repairs</strong>. All biometrics matching filters conform to TVET program standards.
    </p>

    <!-- Official 3-Column Registry Table -->
    <div class="registry-container">
      <table border="1" cellspacing="0" cellpadding="8" style="width: 100%; border-collapse: collapse; margin-top: 15pt; border: 2pt solid #000000;">
        <thead>
          <tr style="background-color: #000000; color: white;">
            <th style="border: 2pt solid #000000; padding: 8pt; text-align: center; width: 45pt; font-weight: bold; font-size: 10.5pt; text-transform: uppercase;">S/N</th>
            <th style="border: 2pt solid #000000; padding: 8pt; text-align: center; width: 120pt; font-weight: bold; font-size: 10.5pt; text-transform: uppercase;">Photograph</th>
            <th style="border: 2pt solid #000000; padding: 8pt; text-align: left; font-weight: bold; font-size: 10.5pt; text-transform: uppercase;">Details</th>
          </tr>
        </thead>
        <tbody>
    `;

    filtered.forEach((b, index) => {
      html += `
          <tr style="page-break-inside: avoid; break-inside: avoid;">
            <td style="border: 1.5pt solid #000000; padding: 10pt; text-align: center; font-weight: bold; font-family: monospace; font-size: 11pt; vertical-align: middle; color: #1e293b; background-color: #ffffff;">
              ${index + 1}
            </td>
            <td style="border: 1.5pt solid #000000; padding: 10pt; text-align: center; vertical-align: middle; background-color: #ffffff;">
              <p style="margin: 0 0 6pt 0; font-weight: bold; font-size: 8.5pt; text-transform: uppercase; color: #000000; text-align: center; font-family: Arial, sans-serif;">Photograph</p>
              <div style="width: 100px; height: 120px; background: #ffffff; border: 1.5pt solid #000000; display: block; margin: 0 auto; overflow: hidden; text-align: center;">
                ${b.photo ? `
                  <img src="${b.photo}" width="100" height="120" style="width: 100px; height: 120px; max-width: 100px; max-height: 120px; object-fit: cover; object-position: center;" />
                ` : `
                  <p style="font-size: 8.5pt; font-weight: bold; color: #94a3b8; font-family: monospace; margin: 30pt 0 0 0; text-align: center;">NO PHOTO</p>
                `}
              </div>
              <p style="margin: 6pt 0 0 0; font-family: monospace; font-size: 8pt; font-weight: bold; color: #64748b; text-align: center;">REF: ${b.id}</p>
            </td>
            <td style="border: 1.5pt solid #000000; padding: 12pt; vertical-align: top; background-color: #ffffff;">
              <p style="margin: 0 0 6pt 0; font-weight: bold; font-size: 8.5pt; text-transform: uppercase; color: #000000; font-family: Arial, sans-serif;">Details</p>
              
              <table style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif; font-size: 9.5pt;">
                <!-- SECTION A -->
                <tr style="background-color: #000000;"><td colspan="2" style="padding: 4pt 8pt; color: #ffffff; font-weight: bold; font-size: 9pt; text-transform: uppercase;">SECTION A: TRAINEE INFORMATION</td></tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Full Name (Surname First):</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000; text-transform: uppercase;">${b.lastName.toUpperCase()}, ${b.firstName.toUpperCase()} ${b.otherName ? b.otherName.toUpperCase() : ""}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Skill Applied For:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000; text-transform: uppercase;">${(b.skillSector || "Computer Hardware and Cell Phone Repairs").toUpperCase()}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">National Identity Number:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.nin || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Phone Number (WhatsApp):</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.phoneNumber || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Email Address:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.email || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Contact Address:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.residentialAddress || "N/A"}, ${b.city || "N/A"}, ${b.state || "N/A"} State</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Date of Birth (DD/MM/YYYY):</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.dateOfBirth || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Highest Qualification:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.educationQualification || "N/A"}</td>
                </tr>

                <!-- SECTION B -->
                <tr style="background-color: #000000;"><td colspan="2" style="padding: 4pt 8pt; color: #ffffff; font-weight: bold; font-size: 9pt; text-transform: uppercase;">SECTION B: PARENT/GUARDIAN INFORMATION</td></tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Name of Parent/Guardian:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.guardianName || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Address of Parent/Guardian:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.guardianAddress || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Phone of Parent/Guardian:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.guardianPhone || "N/A"}</td>
                </tr>

                <!-- SECTION C -->
                <tr style="background-color: #000000;"><td colspan="2" style="padding: 4pt 8pt; color: #ffffff; font-weight: bold; font-size: 9pt; text-transform: uppercase;">SECTION C: SPECIAL NEEDS</td></tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Physical Challenge:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.physicalChallenge || "None"}</td>
                </tr>

                <!-- SECTION D -->
                <tr style="background-color: #000000;"><td colspan="2" style="padding: 4pt 8pt; color: #ffffff; font-weight: bold; font-size: 9pt; text-transform: uppercase;">SECTION D: BANK DETAILS</td></tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Account Holder Name:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000; text-transform: uppercase;">${b.bankAccountHolder || (b.firstName + " " + b.lastName).toUpperCase()}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">BVN Number:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.bvn || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Bank Name:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.bankName || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Bank Sort Code:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.bankSortCode || "N/A"}</td>
                </tr>
                <tr style="border-bottom: 1px dashed #cccccc;">
                  <td style="padding: 4pt; width: 140pt; font-weight: bold; color: #475569;">Bank Account Number:</td>
                  <td style="padding: 4pt; font-weight: bold; color: #000000;">${b.bankAccountNumber || "N/A"}</td>
                </tr>
              </table>

            </td>
          </tr>
      `;
    });

    html += `
        </tbody>
      </table>
    `;

    if (filtered.length === 0) {
      html += `
      <div style="text-align: center; color: #ef4444; font-weight: bold; border: 1px dashed #ef4444; padding: 20pt; border-radius: 4pt;">
        No verified candidates found matching filtered criteria.
      </div>
      `;
    }

    html += `
    </div>

    <table style="width: 100%; margin-top: 30pt; border-collapse: collapse; font-size: 9pt;">
      <tr>
        <td style="width: 45%; vertical-align: top; border-top: 1.5pt solid #000000; padding-top: 8pt;">
          <strong>Trainee Validation</strong><br/><br/>
          Trainee Signature/Thumbprint: _________________<br/><br/>
          Date: _______________________
        </td>
        <td style="width: 10%;"></td>
        <td style="width: 45%; vertical-align: top; border-top: 1.5pt solid #000000; padding-top: 8pt;">
          <strong>Registrar Verification</strong><br/><br/>
          Verified By: __________________<br/><br/>
          Signature: ___________________<br/><br/>
          Date: ________________________
        </td>
      </tr>
    </table>

    <div style="margin-top: 30pt; border-top: 1pt dashed #cbd5e1; padding-top: 10pt; font-size: 7.5pt; color: #64748b; text-align: center;">
      Security Hash Key: 0x8FE0A1959C - Classified Gov Registry | Printed via IDEAS Portal Management System
    </div>
  </div>
</body>
</html>
    `;

    res.setHeader("Content-Type", "application/msword");
    res.setHeader("Content-Disposition", "attachment; filename=ideas_tvet_beneficiaries_photo_album.doc");
    res.status(200).send(html);
  } catch (e: any) {
    res.status(500).send(e.message);
  }
});

// Server boot with Vite middleware
async function startServer() {
  // Gracefully initialize PostgreSQL schema and run migrations
  try {
    await initDb();
  } catch (err) {
    console.error("[SYS] Database setup failure during bootstrap lifecycle:", err);
  }

  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[SYS] Server running on http://localhost:${PORT}`);
  });
}

startServer();
